[
    {
        "Inventory__c": null,
        "Order_Status__c": "Placed",
        "Total_Price__c": "499.0",
        "Order_Date__c": null,
        "warehouse_city__c": null,
        "type": "order__c",
        "DeliveryPartner__c": null,
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "1.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1002",
        "Delivery_Address__c": "12 MG Road, Bangalore, Karnataka",
        "Id": "a08Qy00000TqoknIAB",
        "IsCancelled__c": "false",
        "Delivery_Date__c": null,
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "Placed",
        "Total_Price__c": "110000.0",
        "Order_Date__c": "2025-11-21",
        "warehouse_city__c": "Hyderabad",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001DiOmQIAV",
        "Customer__c": "a04Qy00000EpVg4IAF",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1003",
        "Delivery_Address__c": "Kukatpaly, Hyderabad",
        "Id": "a08Qy00000UkLRZIA3",
        "IsCancelled__c": "false",
        "Delivery_Date__c": null,
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "Placed",
        "Total_Price__c": "110000.0",
        "Order_Date__c": "2025-11-21",
        "warehouse_city__c": "Hyderabad",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001CfL13IAF",
        "Customer__c": "a04Qy00000EpVg4IAF",
        "Quantity__c": "2.0",
        "Invoice__c": "a07Qy00000mzfXUIAY",
        "Order_Id__c": "ORD1004",
        "Delivery_Address__c": "Gachibowli, Hyderabad",
        "Id": "a08Qy00000Un1L3IAJ",
        "IsCancelled__c": "false",
        "Delivery_Date__c": null,
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "packaged",
        "Total_Price__c": "345.0",
        "Order_Date__c": "2025-11-21",
        "warehouse_city__c": "chennai",
        "type": "order__c",
        "DeliveryPartner__c": null,
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1005",
        "Delivery_Address__c": "Road, chennai, tamilnadu",
        "Id": "a08Qy00000Uw0eHIAR",
        "IsCancelled__c": "false",
        "Delivery_Date__c": null,
        "Transit__c": null
    }
]