[
    {
        "Inventory__c": null,
        "Order_Status__c": "packaged",
        "Total_Price__c": "2499.0",
        "Order_Date__c": null,
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy0000186RMzIAM",
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD101",
        "Delivery_Address__c": "sff, Road, Karnataka",
        "Id": "a08Qy00000TqcmsIAB",
        "Delivery_Date__c": null,
        "Transit__c": null
    },
    {
        "Inventory__c": null,
        "Order_Status__c": "Placed",
        "Total_Price__c": "499.0",
        "Order_Date__c": null,
        "type": "order__c",
        "DeliveryPartner__c": null,
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "1.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1002",
        "Delivery_Address__c": "12 MG Road, Bangalore, Karnataka",
        "Id": "a08Qy00000TqoknIAB",
        "Delivery_Date__c": null,
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "packaged",
        "Total_Price__c": "345.0",
        "Order_Date__c": "2025-11-21",
        "type": "order__c",
        "DeliveryPartner__c": null,
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1005",
        "Delivery_Address__c": "Road, chennai, tamilnadu",
        "Id": "a08Qy00000Uw0eHIAR",
        "Delivery_Date__c": null,
        "Transit__c": null
    }
]