#%RAML 1.0
title: sf-sys-api
version: v1
documentation:
  - title: Salesforce System API
    content: The Salesforce System API is responsible for interacting with Salesforce objects
      such as Customers, Orders, Invoices, Inventory, Delivery Partners, and Transit data.

traits:
  errResponse: !include exchange_modules/635159a8-be44-4ed5-a886-bb461c9661c6/trait-error-response/1.0.0/trait-error-response.raml

/api:
  /v1:
    /customers:
      is: [errResponse]
      get:
        description: Retrieve all customers from Salesforce
        responses:
          200:
            body:
              application/json:
                example: !include /Examples/allCustomersDetails.json
      post:
        description: Create a new customer
        body:
          application/json:
            example: !include Examples/customerDetails.json
        responses:
          201:
            body:
              application/json:
                example: !include Examples/customerPostResponse.json

      /{customerId}:
        uriParameters:
          customerId:
            type: string
            description: Unique Customer ID in Salesforce
        get:
          description: Retrieve customer details from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/customerDetails.json
        put:
          description: Update a specific customer record
          body:
            application/json:
              example: !include Examples/customerPutRequest.json
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/customerPutResponse.json

        delete:
          description: Delete a specific customer record
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/customerDeleteResponse.json
    
        /orders:
          get:
            description: Retrieve all orders of the customer from Salesforce
            responses:
              200:
                body:
                  application/json:
                    example: !include /Examples/getAllOrders.json

    /orders:
      is: [errResponse]
      get:
          description: Retrieve all orders from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getAllOrders.json

      post:
        description: Create a new order record in Salesforce
        body:
          application/json:
            example: !include Examples/orderPostRequest.json
        responses:
          201:
            body:
              application/json:
                example: !include Examples/orderPostResponse.json
      /{orderId}:
        uriParameters:
          orderId:
            type: string
            description: Unique Order ID in Salesforce
        get:
          description: Retrieve order details by ID from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getOrderDetails.json
        patch:
          description: Update partial order info
          body:
            application/json:
              example: !include Examples/orderPatchRequest.json
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/orderPatchResponse.json
        
        delete:
          description: Delete an order by order ID.
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/orderCancelledResponse.json          

    /inventory:
      is: [errResponse]
      get:
        description: Retrieve all inventory items from Salesforce
        responses:
          200:
            body:
              application/json:
                example: !include /Examples/getAllInventoryProducts.json
      post:
        description: Create a new inventory item in Salesforce.
        body:
          application/json:
            example: !include Examples/inventoryPostRequest.json
        responses:
          201:
            body:
              application/json:
                example: !include Examples/inventoryPostResponse.json

      /{productId}:
        uriParameters:
          productId:
            type: string
            description: Unique product ID in Salesforce.
        get:
          description: Retrieve inventory item details by product ID
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getInventoryProductDetails.json

        put:
          description: Update an existing inventory item.
          body:
            application/json:
              example: !include Examples/inventoryPutRequest.json
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/inventoryPutResponse.json
        delete:
          description: Delete an inventory item by product ID.
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/inventoryDeleteResponse.json

    /deliveryPartners:
      is: [errResponse]
      get:
          description: Retrieve all delivery partners from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getAllDeliveryPartners.json

      post:
        description: Create a new delivery partner
        body:
          application/json:
            example: !include Examples/deliveryPartnerPostRequest.json
        responses:
          201:
            body:
              application/json:
                example: !include Examples/deliveryPartnerPostResponse.json
     
      /{partnerId}:
        uriParameters:
          partnerId:
            type: string
            description: Unique partner ID in Salesforce.
        get:
          description: Retrieve delivery partner details from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getDeliveryPartnerDetails.json

        put:
          description: Update a specific delivery partner record
          body:
            application/json:
              example: !include Examples/deliveryPartnerPutRequest.json
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/deliveryPartnerPutResponse.json

        delete:
          description: Delete a specific customer record
          body:
            application/json:
              example: !include Examples/deliveryPartnerDeleteResponse.json        
        
        /orders:
          get:
            description: Retrieve all orders assigned to the delivery partner from Salesforce
            responses:
              200:
                body:
                  application/json:
                    example: !include /Examples/getAllAssignedOrders.json
    
    /transits:
      is: [errResponse]
      get:
          description: Retrieve all transits from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getAllTransits.json

      post:
        description: Create a new transit record in Salesforce.
        body:
          application/json:
            example: !include Examples/transitPostRequest.json
        responses:
          201:
            body:
              application/json:
                example: !include Examples/transitPostResponse.json
      /{transitId}:
        uriParameters:
          transitId:
            type: string
            description: Unique Transit ID in Salesforce.
        get:
          description: Retrieve tranist record by ID from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getTransitDetails.json
        
        patch:
          description: Update partial transit info
          body:
            application/json:
              example: !include Examples/transitPatchRequest.json
          responses:
            200:
              body:
                application/json:
                  example: !include Examples/transitPatchResponse.json
    /invoices:
      is: [errResponse]
      get:
          description: Retrieve all all nvoice records from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getAllInvoices.json
      post:
        description: Create a new invoice record in Salesforce.
        body:
          application/json:
            example: !include Examples/invoicePostRequest.json
        responses:
          201:
            body:
              application/json:
                example: !include Examples/invoicePostResponse.json
      /{invoiceId}:
        uriParameters:
          invoiceId:
            type: string
            description: Unique Invoice ID in Salesforce.
        get:
          description: Retrieve invoice record by ID from Salesforce
          responses:
            200:
              body:
                application/json:
                  example: !include /Examples/getInvoiceDetails.json





